Authentication tests
Insidexa/auction pull request #1
Opened 2018-12-06 19:56 UTC by Insidexa

2018-12-09 13:31 UTC, GerashenkoVladimir requested changes

2018-12-09 13:31 UTC, GerashenkoVladimir commented on .env.testing
> +HOST=127.0.0.1
в .gitignor

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/migrations/1543844378070_lots_schema.js
> +      table.integer('status').notNullable().defaultTo(0);
table.enu('status', ['NEW', 'UPDATED', 'DELETED', 'CLOSED'])

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/migrations/1543844378070_lots_schema.js
> +      table.integer('user_id').unsigned().references('id').inTable('users');
по идее пустым быть не должно, потому наверное лучше notNullable()

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/migrations/1543845548817_bids_schema.js
> +      table.integer('user_id').unsigned().references('id').inTable('users');
notNullable()

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/migrations/1543845548817_bids_schema.js
> +      table.datetime('creation_time').notNullable();
по сути можно обойтись и стандартным   table.timestamps(), будет нужное тебе createdAt

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/migrations/1543845669112_orders_schema.js
> +      table.integer('bid_id').unsigned().references('id').inTable('users');
notNullable()

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/migrations/1543937214142_add_is_confirmed_user_column_schema.js
> +      table.boolean('email_confirmed').defaultTo(false);
я бы добавил поле confirmed_at и проверял по его наличию. + есть возможность чекнуть когда законфирмился юзер

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/seeds/LotSeeder.js
> +    users.forEach(async (user) => {
forEach не асинхронный от авейтов твоих нет толку

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/seeds/LotSeeder.js
> +      startTime.setDate(current.getDate() + 10);
для удобной работы с датой используем moment

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/seeds/LotSeeder.js
> +    users.forEach(async (user) => {
я бы выше создал массив объектов с данными и проитетрировался по нему создавая лоты .... надо будет добавить еще пару лотов, просто добавишь в массив еще данных

2018-12-09 13:31 UTC, GerashenkoVladimir commented on database/factory.js
> +Factory.blueprint('App/Models/User', (faker, i, data) => ({
я фабрики раскидал по разным файлам, а в этом только подключаю. так легче ориентироваться когда их уже становится немало

2018-12-09 13:31 UTC, GerashenkoVladimir commented on .gitignore
> -.idea/
package-lock.json убери из .gitignor

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignInController.js
> +'use strict';
я бы отделил контроллеры касающиеся аутентификации в отдельный неймспейс что то типа Auth/SignInController.js

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Validators/SignUp.js
> +      password: 'required|min:8',
подтверждение пароля не валидируешь? не плохо бы было....

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +    return response.send(new ResponseDto.Success(
для сериализации используй это
https://adonisjs.com/docs/4.1/serializers

2018-12-09 13:31 UTC, GerashenkoVladimir commented on test/functional/sign-up.spec.js
> +test('confirmation user', async ({ client }) => {
что будет если я запущу только этот тест?
или этот тест поставлю первым по списку в файле?
у тебя один тест полностью зависит от другого

2018-12-09 13:31 UTC, GerashenkoVladimir commented on test/functional/sign-up.spec.js
> +  const response = await client
тут у тебя создается 2 токена на подтверждение вместо 1, разобраться бы

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignUpController.js
> +    const uuid = params.uuidToken;
почему не confirmationToken?

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignUpController.js
> +    const uuid = params.uuidToken;
называешь переменную uuid а там у нас токен лежит.... семантически не верно

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignUpController.js
> +    const token = await Token.query().confirmToken().where('token', uuid).firstOrFail();
ты смотрел что в респонсе приходит когда не находит токен?

уверен что это нужно в респонсе 
{ message: 'ModelNotFoundException',
  errors: 'E_MISSING_DATABASE_ROW: Cannot find database row for Token model\n> More details: https://err.sh/adonisjs/errors/E_MISSING_DATABASE_ROW' }

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignUpController.js
> +    if (!token.isActive()) {
можно сразу искать сразу не ревоукнутые токены
+ к чему вообще показывать что такой токен есть но ревоукнутый? отдаешь 404 что нет токена и все
не совсем понятно зачем хранить конфирм токены после того как они ревоукнулись
я бы конфирм токены(то же касается и пассворд токенов) хранил бы в юзере

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignUpController.js
> +    await Database.transaction(async () => {
хранил бы токен в юзере не пришлось бы транзакции юзать

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignUpController.js
> +      user.emailConfirmed();
1. метод по сути бесполезный. можно напрямую сетить
2. название сбивает с толку. сразу не понятно что он делает

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignInController.js
> +    if (user.isNotConfirmed()) {
!user.email_confirmed - вполне достаточно 
не плоди бесполезные методы

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Models/User.js
> +    return this.email_confirmed === false;
метод бесполезный но разве этого не будет достаточно ?
return !this.email_confirmed

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Models/User.js
> +  isConfirmed () {
return this.email_confirmed

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignInController.js
> +    const user = await User.findBy('email', email);
const user = await User.findBy({ email, email_confirmed: true });
я бы сразу искал законфирмленого юзера

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignInController.js
> +        [],
зачем пустой массив передаешь?

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignInController.js
> +    const token = await user.createPasswordToken();
не совсем понятно зачем юзера знать протокены и все что связано с конфирмом?
я бы для этого возможно сервис сделал или даже в контроллере

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Validators/PasswordUpdate.js
> +      password: 'required|min:8',
password: `required|confirmed` - вот так на конфирм проверяй

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignInController.js
> +        personal: token,
лучше в хедерах передавай токен

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Models/User.js
> +    const notification = ioc.use('App/Notification');
просто use('App/Notification')
все юзы вверху файла

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Models/User.js
> +const uuidv4 = require('uuid/v4');
ioc вызывать не надо, доступен через  use

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Models/User.js
> +const uuidv4 = require('uuid/v4');
никаких реквайров по коду
если нужно что то "утильное" мы выносим в сервис с общими хелперами (например Utils)

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Models/User.js
> +  async confirmEmail () {
в ивенты засунь и вызывай в хуках как и сейчас .... сильно много твой юзер знает
https://adonisjs.com/docs/4.1/events

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Models/User.js
> +  generateConfirmHTML (token) {
это тут вообще не к чему
юзаем темплейты имейлов
https://adonisjs.com/docs/4.1/mail

2018-12-09 13:31 UTC, GerashenkoVladimir commented on config/services.js
> +ioc.bind('App/Notification', (app) => {
https://adonisjs.com/docs/4.1/service-providers
вот так сервисы биндятся

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Services/Notification.js
> +class Notification {
для каких целей ты еще собираешься использовать этот сервис?

2018-12-09 13:31 UTC, GerashenkoVladimir commented on providers/AgeCheckRuleProvider.js
> +const { ServiceProvider } = require('@adonisjs/fold');
вообще не для этого используешь сервис провайдер
читай о сервисах

2018-12-09 13:31 UTC, GerashenkoVladimir commented on test/functional/password-recovery.spec.js
> +    .post('api/password/recovery')
создавай роуты по имени а не хард кодом
Route.url('route_name')

2018-12-09 13:31 UTC, GerashenkoVladimir commented on test/functional/password-recovery.spec.js
> +  await Database
почему не модель юзера?

2018-12-09 13:31 UTC, GerashenkoVladimir commented on app/Models/Token.js
> +const PASSWORD_TOKEN = 'password';
у тебя тут токен хранится или все таки так тип обозначаешь?

2018-12-09 13:31 UTC, GerashenkoVladimir commented on test/functional/password-recovery.spec.js
> +  const [userId] = await Database
почему не модель?

2018-12-09 13:31 UTC, GerashenkoVladimir commented on test/functional/password-recovery.spec.js
> +    message: 'ModelNotFoundException',
по твоему норм сообщение об шибке для фронта?

2018-12-09 13:31 UTC, GerashenkoVladimir commented on test/functional/sign-up.spec.js
> +  User.addHook('afterCreate', async (instance) => {
зачем?

2018-12-09 13:31 UTC, GerashenkoVladimir commented on test/functional/sign-up.spec.js
> +test('sign up user', async ({ assert, client }) => {
разбей на 2 теста 
1. тестит создание
2. тестит отсылку мыла
ну и остальных тестов тоже касается где слишком много проверок

2018-12-09 13:31 UTC, GerashenkoVladimir commented on test/functional/sign-up.spec.js
> +  response.assertStatus(403);
почему 403?
403 ошибка доступа

2018-12-09 13:39 UTC, Insidexa commented on database/migrations/1543844378070_lots_schema.js
> +      table.integer('status').notNullable().defaultTo(0);
не согласен, enum плохо переносятся между базами или вообще не переносится

2018-12-09 13:56 UTC, Insidexa commented on database/migrations/1543937214142_add_is_confirmed_user_column_schema.js
> +      table.boolean('email_confirmed').defaultTo(false);
можно пример когда нужно знать в какое время законфирмился юзер ? реальный кейс

2018-12-09 13:59 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +    return response.send(new ResponseDto.Success(
`.toJSON()` ?

2018-12-09 14:05 UTC, Insidexa commented on app/Models/User.js
> +    const notification = ioc.use('App/Notification');
Это контейнер, он зависимости подсовывает, нельзя просто так взять и заимпортить то что требует зависимость

2018-12-09 14:07 UTC, Insidexa commented on app/Models/User.js
> +  generateConfirmHTML (token) {
согласен, забыл

2018-12-09 14:09 UTC, Insidexa commented on app/Models/User.js
> +const uuidv4 = require('uuid/v4');
Общий сервисы типа Utils ни о чем не говорят с чем они именно работают и что там внутри, эт такой себе god object

2018-12-09 14:18 UTC, Insidexa commented on providers/AgeCheckRuleProvider.js
> +const { ServiceProvider } = require('@adonisjs/fold');
https://adonisjs.com/docs/4.1/validator#_extending_validator
можно расширять в сервис провайдерах или хуках
может и не нужно было мне для каждого правила создавать провайдер, но тут я не согласен
сервисы не причем тут

2018-12-09 14:19 UTC, Insidexa commented on test/functional/password-recovery.spec.js
> +    .post('api/password/recovery')
согласен, забыл

2018-12-09 14:19 UTC, Insidexa commented on app/Models/Token.js
> +const PASSWORD_TOKEN = 'password';
тип токена

2018-12-09 14:29 UTC, Insidexa commented on .gitignore
> -.idea/
(-) `package-lock.json` согласен
зачем `.idea` ? в этом есть какой-то смысл, но он мне не очевиден
у меня темная тема, а тот кто скачает репозиторий со светлой Idea получит темную или наоборот
и кучу других настроек которые для человека могут быть неприемлемыми

2018-12-09 14:43 UTC, Insidexa commented on database/seeds/LotSeeder.js
> +      startTime.setDate(current.getDate() + 10);
хотел подключить честно, но здесь немного я работал с датой
ладно это в конце поправлю

2018-12-09 14:55 UTC, Insidexa commented on database/seeds/LotSeeder.js
> +    users.forEach(async (user) => {
я в другой ветке сидеры переписал

2018-12-09 14:57 UTC, Insidexa commented on app/Controllers/Http/SignUpController.js
> +    await Database.transaction(async () => {
(-) токены же разные бывают, все хранить вместе с данными юзера ?

2018-12-09 14:58 UTC, Insidexa commented on app/Controllers/Http/SignInController.js
> +    const user = await User.findBy('email', email);
(-) в тз я не видел смены пароля для залогиненого юзера

2018-12-10 07:27 UTC, GerashenkoVladimir commented on .gitignore
> -.idea/
при чем тут .idea?  я вообще о ней не говорил

2018-12-10 07:29 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +    return response.send(new ResponseDto.Success(
tojson оно не явно и так дергает когда передаешь в респонс объект

2018-12-10 07:31 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignInController.js
> +    const user = await User.findBy('email', email);
я о законфирмленом а не о залогиненом тут пишу........на и если нет в тз то ок

2018-12-10 07:34 UTC, GerashenkoVladimir commented on app/Controllers/Http/SignUpController.js
> +    await Database.transaction(async () => {
на рельсах есть гем "device auth token" там вполне себе успешно хранятся токены конфирма и сброса в юзере а токены аутентификации отдельно
плюс еще у адониса далеко не гладко все с транзакциями, иногда не может их адекватно обработать.....ну это твой выбор ..... настаивать не буду

2018-12-10 07:35 UTC, GerashenkoVladimir commented on app/Models/Token.js
> +const PASSWORD_TOKEN = 'password';
ну я потому и спросил
по названию можно подумать что там токен и лежит.....почему спросил....в тестах немного сбило с толку

2018-12-10 07:39 UTC, GerashenkoVladimir commented on app/Models/User.js
> +const uuidv4 = require('uuid/v4');
god object был бы если бы у него было куча интерфейсов и отвечал он за все подряд......захочешь поменять "генератор хешей"(токенов) будем по всему коду реквайры переписывать....не хочешь делать утильный класс, можешь обернуть в какой то маленький сервис

2018-12-10 07:41 UTC, GerashenkoVladimir commented on app/Models/User.js
> +    const notification = ioc.use('App/Notification');
use и есть контейнер ...это не просто "модный" реквайр 
неявно он пытается выдергнуть из конетейнера зависимостей если не находит то автолоадом реквайрит
и да я знаю что такое контейнер зависимостей......

2018-12-10 07:53 UTC, GerashenkoVladimir commented on database/migrations/1543844378070_lots_schema.js
> +      table.integer('status').notNullable().defaultTo(0);
там текстовое поле будет

2018-12-10 07:55 UTC, GerashenkoVladimir commented on database/migrations/1543937214142_add_is_confirmed_user_column_schema.js
> +      table.boolean('email_confirmed').defaultTo(false);
есть пример решения на рельсах devise_token_auth

2018-12-10 07:55 UTC, GerashenkoVladimir commented on database/seeds/LotSeeder.js
> +    users.forEach(async (user) => {
+

2018-12-10 07:56 UTC, GerashenkoVladimir commented on database/seeds/LotSeeder.js
> +      startTime.setDate(current.getDate() + 10);
не критично.... просто к слову

2018-12-10 08:02 UTC, GerashenkoVladimir commented on providers/AgeCheckRuleProvider.js
> +const { ServiceProvider } = require('@adonisjs/fold');
а не смущает что ты СЕРВИС провайдер юзаешь для имплементации правила для валидатора?

2018-12-10 08:35 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +    return response.send(new ResponseDto.Success(
я тут юзаю класс wrapper DTO что бы респонс был всегда в `data`, ответ был по структуре одинаковый
тоже самое с ошибками

2018-12-10 08:40 UTC, Insidexa commented on app/Models/User.js
> +const uuidv4 = require('uuid/v4');
понял насчет require, согласен

2018-12-10 08:56 UTC, Insidexa commented on providers/AgeCheckRuleProvider.js
> +const { ServiceProvider } = require('@adonisjs/fold');
теперь кастомные правила валидации в одном провайдере `CustomValidationRulesProvider`

2018-12-10 09:55 UTC, Insidexa commented on app/Validators/PasswordUpdate.js
> +      password: 'required|min:8',
да, я это нашел, юзал так в другой ветке уже

2018-12-10 12:06 UTC, Insidexa commented on .gitignore
> -.idea/
сорян, ошибочка вышла, просто стоит `- .idea/`
подумал так отмечено для удаления

2018-12-10 12:22 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +    return response.send(new ResponseDto.Success(
это да, но твой dto чего не знает ни о релейшинах ни о сериалайзере
и раз реч зашла о dto,  то структурируй его нормально, а то 3 класа в один файл свалил.....давай следовать общему стилю проекта и фрейма
- к слову у нас все рубисты оборачивают в resource: {}

2018-12-10 12:25 UTC, GerashenkoVladimir commented on app/Models/Order.js
> +module.exports.PENDING_STATUS = PENDING_STATUS;
почему не так Order.PENDING_STATUS = 0?

2018-12-10 12:33 UTC, GerashenkoVladimir commented on providers/AgeCheckRuleProvider.js
> +const { ServiceProvider } = require('@adonisjs/fold');
вынеси в отдельный файлик (например в папку Validator/CustomRules) так будет правильнее 
и в первую очередь люди кастомные правила будут смотреть там, а не в сервис провайдерах
в сервис провайдере по сути подключаются сервисы в IoC и сетятся алиасы для их вызова....ну максимум для иницализации какой то короткий кусок кода .... пример с их же доки
https://adonisjs.com/docs/4.1/service-providers#_service_provider

2018-12-10 12:37 UTC, GerashenkoVladimir commented on app/Dto/ResponseDto.js
> +  static Error (message, errors) {
название метода с большой буквы?

2018-12-10 13:53 UTC, Insidexa commented on app/Models/Order.js
> +module.exports.PENDING_STATUS = PENDING_STATUS;
можно и так, привычка такая

2018-12-10 13:56 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +    return response.send(new ResponseDto.Success(
но не всегда же возвращается модель, а там где нету модели как юзать сериализатор ?

2018-12-10 14:48 UTC, Insidexa commented on .env.testing
> +HOST=127.0.0.1
+

2018-12-10 14:48 UTC, Insidexa commented on database/migrations/1543844378070_lots_schema.js
> +      table.integer('user_id').unsigned().references('id').inTable('users');
+

2018-12-10 14:48 UTC, Insidexa commented on database/migrations/1543845548817_bids_schema.js
> +      table.integer('user_id').unsigned().references('id').inTable('users');
+

2018-12-10 14:49 UTC, Insidexa commented on test/functional/password-recovery.spec.js
> +  const [userId] = await Database
+

2018-12-10 14:49 UTC, Insidexa commented on app/Dto/ResponseDto.js
> +  static Error (message, errors) {
+

2018-12-10 14:50 UTC, Insidexa commented on database/migrations/1543845669112_orders_schema.js
> +      table.integer('bid_id').unsigned().references('id').inTable('users');
+

2018-12-10 14:50 UTC, Insidexa commented on database/seeds/LotSeeder.js
> +    users.forEach(async (user) => {
это в другой ветке переписано по другому

2018-12-10 14:50 UTC, Insidexa commented on database/factory.js
> +Factory.blueprint('App/Models/User', (faker, i, data) => ({
пока не раскидал, на будущее запомнил

2018-12-10 14:50 UTC, Insidexa commented on .gitignore
> -.idea/
+

2018-12-10 14:51 UTC, Insidexa commented on app/Controllers/Http/SignInController.js
> +'use strict';
+

2018-12-10 14:51 UTC, Insidexa commented on app/Validators/SignUp.js
> +      password: 'required|min:8',
+

2018-12-10 14:51 UTC, Insidexa commented on app/Controllers/Http/SignUpController.js
> +    const uuid = params.uuidToken;
+

2018-12-10 14:52 UTC, Insidexa commented on app/Controllers/Http/SignUpController.js
> +    const uuid = params.uuidToken;
+

2018-12-10 14:52 UTC, Insidexa commented on app/Controllers/Http/SignUpController.js
> +      user.emailConfirmed();
+

2018-12-10 14:52 UTC, Insidexa commented on app/Controllers/Http/SignInController.js
> +    if (user.isNotConfirmed()) {
+

2018-12-10 14:52 UTC, Insidexa commented on app/Models/User.js
> +    return this.email_confirmed === false;
+

2018-12-10 14:53 UTC, Insidexa commented on app/Controllers/Http/SignInController.js
> +    const token = await user.createPasswordToken();
+

2018-12-10 14:53 UTC, Insidexa commented on app/Controllers/Http/SignInController.js
> +        personal: token,
+

2018-12-10 14:53 UTC, Insidexa commented on app/Models/User.js
> +const uuidv4 = require('uuid/v4');
+

2018-12-10 14:53 UTC, Insidexa commented on app/Models/User.js
> +  generateConfirmHTML (token) {
+

2018-12-10 14:53 UTC, Insidexa commented on providers/AgeCheckRuleProvider.js
> +const { ServiceProvider } = require('@adonisjs/fold');
+

2018-12-10 14:53 UTC, Insidexa commented on test/functional/password-recovery.spec.js
> +    .post('api/password/recovery')
+

2018-12-10 14:53 UTC, Insidexa commented on test/functional/password-recovery.spec.js
> +  await Database
+

2018-12-11 07:21 UTC, Insidexa commented on app/Controllers/Http/SignUpController.js
> +    if (!token.isActive()) {
так же в laravel миграциях сделано )

2018-12-11 08:22 UTC, GerashenkoVladimir requested changes

2018-12-11 08:22 UTC, GerashenkoVladimir commented on app/Controllers/Http/Auth/SignInController.js
> +    Mail.send('emails.password-reset', { token: token.token }, (message) => {
через ивенты не захотел сделать?
https://adonisjs.com/docs/4.1/events

2018-12-11 08:22 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +    this.repository = ioc.use('App/Repositories/LotRepository');
не надо реквайритm ioc юзай глабальный метод  use
https://adonisjs.com/docs/4.1/ioc-container#_resolving_dependencies

2018-12-11 08:22 UTC, GerashenkoVladimir commented on app/Dto/ErrorDto.js
> +class ErrorDto {
'use strict' не забывай

2018-12-11 08:28 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +    this.repository = ioc.use('App/Repositories/LotRepository');
да это зафиксю в другой ветке

2018-12-11 08:28 UTC, Insidexa commented on app/Controllers/Http/Auth/SignInController.js
> +    Mail.send('emails.password-reset', { token: token.token }, (message) => {
не

2018-12-11 09:39 UTC, Insidexa commented on app/Dto/ErrorDto.js
> +class ErrorDto {
+

2018-12-11 11:00 UTC, GerashenkoVladimir approved these changes

2018-12-13 19:01 UTC, closed without merging