Lots
Insidexa/auction pull request #3
Opened 2018-12-13 19:03 UTC by Insidexa

2018-12-13 21:24 UTC, GerashenkoVladimir requested changes

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Controllers/Http/Auth/SignInController.js
> +    Mail.send('emails.password-reset', { token: token.token }, (message) => {
уже вроде писал
почему в ивенты не засунешь?

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Controllers/Http/Auth/SignInController.js
>        null,
к чему null?

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Controllers/Http/Auth/SignInController.js
>      const user = await User.findBy('email', email);
User.findBy({email});

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Validators/SignIn.js
>        password: 'required|min:8',
ты не должен говорить что нет такого имейла
просто 404
за это отвечает контроллер, а валидатор лишь проверяет что бы имейл был валидный

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/auth/sign-in.spec.js
> +  response.assertStatus(400);
404

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Controllers/Http/Auth/SignUpController.js
> +    const userRequest = request.only([
в отдельный метод можно вынести что бы не нагромождалось

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Controllers/Http/Auth/SignUpController.js
> +    Mail.send('emails.user-confirmation', { token: token.token }, (message) => {
в ивенты

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +  async my ({ params, response, auth }) {
что думаешь по поводу объединения с индексной ручкой?

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +    if (image) {
попробуй зашить в хуки сохранение имейджей

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +      null,
убери

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Models/Lot.js
> +        return query.where('user_id', user.id);
код дублируешь (return query.where('user_id', user.id);)
туду-шку убери

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Models/Lot.js
> +  statusProcessing () {
setInProcessStatus() как по мне явно понятнее
дает понять что метод делает
то же касается и остальных метов

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Models/Token.js
>  module.exports = Token;
почему не сетишь как на подобие "статичных" свойств класса?

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Utils/FS.js
> +function fullPathUpload (image) {
оформи уже в класс это все
а то у нас весь проект в классах а тут свалка функций

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Utils/FS.js
> +module.exports.fullPathUpload = fullPathUpload;
module.exports = {
fullPathUpload,
removeIfExists,
saveImageFromBase64
}

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Validators/CustomRules/AgeCheck.js
> +        throw new Error(`ageCheck validation failed on ${field}. Must be less than ${rangeAge}`);
могу ошибаться, но ты  скорее всего не сможешь переопределить еррор месседж в самом валидаторе, а это не есть гуд

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Validators/CustomRules/AgeCheck.js
> +async function ageCheck (data, field, message, args, get) {
https://indicative.adonisjs.com/docs/before
посмотри это лучше

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Validators/CustomRules/Exists.js
> +async function exists (data, field, message, args, get) {
такое правило есть тоже

2018-12-13 21:24 UTC, GerashenkoVladimir commented on app/Validators/Lot.js
> +  get validateAll () {
сделай базовый валидатор и наследуйся от него что бы не дублировать методы

2018-12-13 21:24 UTC, GerashenkoVladimir commented on database/factory.js
>    current_price: 10.33,
лучше юзать фейкер

2018-12-13 21:24 UTC, GerashenkoVladimir commented on database/migrations/1503248427886_token.js
> +      table.integer('user_id')
поменял файл миграции после того как смержил с дев веткой?

2018-12-13 21:24 UTC, GerashenkoVladimir commented on database/seeds/AuctionTestDataSeeder.js
> +      await Factory.model('App/Models/User').create({
лучше создать массив с данными и циклом по нему пройтись

2018-12-13 21:24 UTC, GerashenkoVladimir commented on docker-compose.yml
> +  redis:
докер используешь?

2018-12-13 21:24 UTC, GerashenkoVladimir commented on start/routes.js
> +    Route
для круда юзаем resource
нет надобности объявлять каждый роут по отдельности

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/auth/password-recovery.spec.js
> +  const token = await Token.first();
user.tokens().first()
лучше так

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/auth/password-recovery.spec.js
> +  assert.equal(recentEmail.message.to[0].address, email);
не мешало бы проверить правильно ли сгенерирована ссылка
на тот ли хост и тд
валидность самого сообщения

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/auth/sign-in.spec.js
> +    message: 'ValidationException',
это не ошибка валидации

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/auth/sign-in.spec.js
> +    message: 'PasswordMisMatchException',
404 и все
не надо уточнять по какой причини
лишняя инфа 
не правильно введен логин или пароль и все

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/auth/sign-in.spec.js
> +  response.assertStatus(200);
body надо бы тоже проверит

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/auth/sign-up.spec.js
> +    birth_day: '1900-01-02',
1900 год?

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/auth/sign-up.spec.js
> +  const userDB = await User.findBy('email', userRequest.email);
не плохо бы проверить что количество юзеров увеличилось на +1

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/auth/sign-up.spec.js
> +  assert.equal(recentEmail.message.to[0].address, userRequest.email);
текст имейла проверяй

2018-12-13 21:24 UTC, GerashenkoVladimir commented on test/functional/http/lot.spec.js
> +    await removeIfExists(lot.image);
в хуки модели засунь

2018-12-14 05:41 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +  async my ({ params, response, auth }) {
вы выйдет, в index лоты только в процессе, а в my все и + фильтрация

2018-12-14 05:54 UTC, Insidexa commented on app/Controllers/Http/Auth/SignInController.js
>        null,
а что ответить ?

2018-12-14 06:13 UTC, Insidexa commented on docker-compose.yml
> +  redis:
+, не хочу ставить на хост машину и возиться с этим

2018-12-14 06:15 UTC, Insidexa commented on test/functional/http/auth/password-recovery.spec.js
> +  const token = await Token.first();
но здесь нигде пользователя не объявляю

2018-12-14 06:17 UTC, Insidexa commented on test/functional/http/auth/sign-in.spec.js
> +    message: 'PasswordMisMatchException',
тут я не понимаю, как можно ответить 404 при создании пользователя когда пароли не совпадают

2018-12-14 06:32 UTC, Insidexa commented on app/Controllers/Http/Auth/SignInController.js
> +    Mail.send('emails.password-reset', { token: token.token }, (message) => {
ивент файрить с контроллера, слушать в start/events и юзать listeners ?

2018-12-14 07:22 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +      null,
сделаю так `resposen.status(204).send()`

2018-12-14 07:34 UTC, Insidexa commented on app/Validators/SignIn.js
>        password: 'required|min:8',
+
я че так делаю, видел такие практики, если так правильно - запомню

2018-12-14 07:39 UTC, Insidexa commented on app/Models/Token.js
>  module.exports = Token;
не понял

2018-12-14 07:58 UTC, Insidexa commented on app/Validators/CustomRules/AgeCheck.js
> +async function ageCheck (data, field, message, args, get) {
т.е. нужно от текущей даты высчитать 21 год и поместить дату сюда та что вышла
по мне так себе, со своим валидатором проще, могу и чекнуть равен ли возраст

2018-12-14 07:58 UTC, Insidexa commented on app/Validators/CustomRules/Exists.js
> +async function exists (data, field, message, args, get) {
не нашел, вообщем удалил я этот валидатор, он оказался ненужным

2018-12-14 08:11 UTC, Insidexa commented on app/Utils/FS.js
> +function fullPathUpload (image) {
это переделаю, а насчет ImageService не могу я его засунуть в ioc, там в конструктор передается input для sharp
ImageService и TokenMaker пока бессмысленно, навешу только альясы

2018-12-14 08:19 UTC, Insidexa commented on database/factory.js
>    current_price: 10.33,
я это поле удалю с faker, так как лучше самому генерить, а ссылки с фейкера будут не рабочими, это только вызовет проблемы, там ли локальный путь или url

2018-12-14 09:11 UTC, Insidexa commented on database/migrations/1503248427886_token.js
> +      table.integer('user_id')
случайно вышло ((

2018-12-14 09:14 UTC, Insidexa commented on test/functional/http/auth/password-recovery.spec.js
> +  assert.equal(recentEmail.message.to[0].address, email);
само сообщение считаю проверять бессмысленным, оно может быть большим, а если туда нужно будет кучу данных подготовить, то вообще жесть

2018-12-14 09:32 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +    if (image) {
вышло кривовато, проблема крылась когда нужно обновить лот ( у него есть имейдж )
и при загрузке новой фотки, нужно удалить старую, старую не получу, так как новая филится туда
пришлось дергать оригинальные атрибуты которые пришли с бд и еще не обновились

2018-12-14 09:33 UTC, Insidexa commented on app/Utils/FS.js
> +module.exports.fullPathUpload = fullPathUpload;
(-), перенес в класс

2018-12-14 09:41 UTC, Insidexa commented on test/functional/http/auth/sign-up.spec.js
> +  const userDB = await User.findBy('email', userRequest.email);
вместо поиске по email ?
т.е. поиск по email это точное совпадение

2018-12-14 09:43 UTC, Insidexa commented on test/functional/http/auth/sign-up.spec.js
> +  assert.equal(recentEmail.message.to[0].address, userRequest.email);
само сообщение считаю проверять бессмысленным, оно может быть большим, а если туда нужно будет кучу данных подготовить, то вообще жесть
(-)

2018-12-14 10:55 UTC, Insidexa commented on app/Validators/CustomRules/AgeCheck.js
> +        throw new Error(`ageCheck validation failed on ${field}. Must be less than ${rangeAge}`);
да, не получается, заменил на after

2018-12-14 11:44 UTC, Insidexa commented on database/seeds/AuctionTestDataSeeder.js
> +      await Factory.model('App/Models/User').create({
(-) но там же разные email которые нужны и должны быть явно определены
тут заранее явное к-во данных для работы через swagger

2018-12-14 11:46 UTC, Insidexa commented on test/functional/http/lot.spec.js
> +    await removeIfExists(lot.image);
+

2018-12-14 11:46 UTC, Insidexa commented on test/functional/http/auth/sign-up.spec.js
> +  assert.equal(recentEmail.message.to[0].address, userRequest.email);
+

2018-12-14 11:46 UTC, Insidexa commented on test/functional/http/auth/sign-up.spec.js
> +    birth_day: '1900-01-02',
+, юзнул momentjs

2018-12-14 11:46 UTC, Insidexa commented on test/functional/http/auth/sign-in.spec.js
> +  response.assertStatus(200);
+

2018-12-14 11:46 UTC, Insidexa commented on test/functional/http/auth/sign-in.spec.js
> +  response.assertStatus(400);
+

2018-12-14 11:46 UTC, Insidexa commented on app/Validators/SignIn.js
>        password: 'required|min:8',
+
я почему так делаю, видел такие практики, если так правильно - запомню

2018-12-14 11:46 UTC, Insidexa commented on app/Controllers/Http/Auth/SignInController.js
>      const user = await User.findBy('email', email);
+

2018-12-14 11:46 UTC, Insidexa commented on app/Controllers/Http/Auth/SignInController.js
> +    Mail.send('emails.password-reset', { token: token.token }, (message) => {
+

2018-12-14 11:47 UTC, Insidexa commented on app/Controllers/Http/Auth/SignUpController.js
> +    const userRequest = request.only([
+

2018-12-14 11:47 UTC, Insidexa commented on app/Controllers/Http/Auth/SignUpController.js
> +    Mail.send('emails.user-confirmation', { token: token.token }, (message) => {
+

2018-12-14 11:47 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +    if (image) {
+

2018-12-14 11:47 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +      null,
+

2018-12-14 11:47 UTC, Insidexa commented on app/Models/Lot.js
> +        return query.where('user_id', user.id);
+

2018-12-14 11:47 UTC, Insidexa commented on app/Models/Lot.js
> +  statusProcessing () {
+

2018-12-14 11:48 UTC, Insidexa commented on app/Validators/CustomRules/AgeCheck.js
> +        throw new Error(`ageCheck validation failed on ${field}. Must be less than ${rangeAge}`);
+

2018-12-14 11:48 UTC, Insidexa commented on app/Validators/CustomRules/AgeCheck.js
> +async function ageCheck (data, field, message, args, get) {
да спасибо, не заметил, норм вышло

2018-12-14 11:48 UTC, Insidexa commented on app/Validators/CustomRules/Exists.js
> +async function exists (data, field, message, args, get) {
+

2018-12-14 11:48 UTC, Insidexa commented on app/Validators/Lot.js
> +  get validateAll () {
+

2018-12-14 11:49 UTC, Insidexa commented on start/routes.js
> +    Route
я объявил изначально resource, потом удалил когда нужно было кастомные роуты добавлять в resource

2018-12-14 11:49 UTC, Insidexa commented on test/functional/http/auth/password-recovery.spec.js
> +  assert.equal(recentEmail.message.to[0].address, email);
+

2018-12-14 11:49 UTC, Insidexa commented on test/functional/http/auth/sign-in.spec.js
> +    message: 'ValidationException',
+

2018-12-14 11:49 UTC, Insidexa commented on test/functional/http/auth/sign-in.spec.js
> +    message: 'PasswordMisMatchException',
+

2018-12-15 12:51 UTC, GerashenkoVladimir requested changes

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Controllers/Http/Auth/SignInController.js
>        null,
я о том что нет смысла null передавать

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Models/Token.js
>  module.exports = Token;
Token.CONFIRMATION_TOKEN = 'confirmation';

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Validators/SignIn.js
>        password: 'required|min:8',
это при регистрации можно сказать что такой имейл занят

2018-12-15 12:51 UTC, GerashenkoVladimir commented on database/factory.js
>    current_price: 10.33,
я о current_price
а о имейдже ..... лучше сразу передавай из data тогда

2018-12-15 12:51 UTC, GerashenkoVladimir commented on database/seeds/AuctionTestDataSeeder.js
> +      await Factory.model('App/Models/User').create({
[
   {email: 'some@example.com'},
   {email: 'another@example.com'},
]
а кто мешает тебе создать нужные данные и итерироваться по ним создавая юзеров или лоты?

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +  async all ({ response, params }) {
REST!!! 
было же нормально 
я говорил только о нормальной фильтрации

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +  async self ({ params, response, auth }) {
по сути 2 индексовые ручки и ты в них почти одно и то же делаешь
либо объясни почему ты объединять не хочешь либо сделай как говорю

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Jobs/LotEnd.js
> +class LotStart {
имя класса
копипаст

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Models/Hooks/LotHook.js
> +const LotHook = {};
class LotHook {
  static afterCreate() {
  }
}

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Models/Hooks/LotHook.js
> +    lot.calculateStartDelay(),
от явно этим не модель должна заниматься
зачем вообще модели нужно знать что есть какие то джобы?

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Models/Hooks/LotHook.js
> +  await Redis.set(`lot_${id}_queue`, JSON.stringify({
по идее kue сам умеет с редисом работать
ты доку читаешь?
https://github.com/Automattic/kue#creating-jobs

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Models/Hooks/LotHook.js
> +  const endJob = await JobUtils.promisifyRunJob(
по идее весь этот кусок кода надо бы запихнуть в какую то сущность которая умеет сетить джобы и все остальное, а в хуке вызвать метод, передать аргументы и все

2018-12-15 12:51 UTC, GerashenkoVladimir commented on app/Validators/Lot.js
> +    const minCurrentTime = Moment().format(LotModel.formatType());
как это минимальное текущее время?)

2018-12-15 12:51 UTC, GerashenkoVladimir commented on config/services.js
> +  const FSService = app.use('App/Services/FSService');
уже писал что для биндинга сервисов есть сервис провайдеры
используй!

2018-12-15 12:51 UTC, GerashenkoVladimir commented on providers/KueProvider.js
> +    Kue.app.listen(3000);
зачем подымаешь UI сервер?

2018-12-15 12:51 UTC, GerashenkoVladimir commented on start/routes.js
>    .prefix('api');
namespace('Auth')

2018-12-15 12:51 UTC, GerashenkoVladimir commented on test/functional/http/lot.spec.js
> +  for (const lot of lots.rows) {
почему циклом?
не можешь удалить все сразу как юзеров?

2018-12-15 12:51 UTC, GerashenkoVladimir commented on test/functional/http/lot.spec.js
> +  await Lot.query().delete();
в beforeEach или afterEach

2018-12-15 12:51 UTC, GerashenkoVladimir commented on test/functional/http/lot.spec.js
> +  const lot = await Lot.first();
вот таким образом доставая из бд-шки, можешь потом долго дебажить и не понимать почему валится и почему не тот лот сфетчило(могут остаться от предыдущих тестов или что то подобное)

2018-12-15 12:51 UTC, GerashenkoVladimir commented on test/functional/http/lot.spec.js
> +    data: {
что за вложенность странная?

2018-12-15 12:51 UTC, GerashenkoVladimir commented on test/unit/validators/lot.spec.js
> +  response.assertStatus(400);
422

2018-12-15 12:57 UTC, Insidexa commented on test/functional/http/lot.spec.js
> +    data: {
респонс оборачивается в dto

2018-12-15 12:59 UTC, Insidexa commented on app/Models/Hooks/LotHook.js
> +  await Redis.set(`lot_${id}_queue`, JSON.stringify({
умеет конечно, там джобы, а мне нужно именно в редис данные записать, причем тут kue

2018-12-15 12:59 UTC, Insidexa commented on app/Models/Hooks/LotHook.js
> +    lot.calculateStartDelay(),
все что по джобам, еще не доделал

2018-12-15 13:00 UTC, Insidexa commented on app/Controllers/Http/LotController.js
> +  async self ({ params, response, auth }) {
я написал почему выше

2018-12-15 14:17 UTC, Insidexa commented on app/Models/Hooks/LotHook.js
> +    lot.calculateStartDelay(),
да и походу буду в контроллере джобу запускать, сервис для лотов напишу
ибо при сидах если юзать редис в хуках, процесс не стопается, а висит

2018-12-15 14:56 UTC, Insidexa commented on test/unit/validators/lot.spec.js
> +  response.assertStatus(400);
так валидатор кидает 400, не я же, такой код по умолчанию

2018-12-15 16:36 UTC, Insidexa commented on test/functional/http/lot.spec.js
> +  await Lot.query().delete();
у beforeEach нету смысла ибо там для теста создаются данные, а в afterEach очищаются
в этом тесте `lot destroy not found` мне нужны данные для теста, по этому удалять их в forEach бессмысленно, а afterEach уже после теста идет
я это понимал и сделал так

2018-12-17 07:41 UTC, GerashenkoVladimir requested changes

2018-12-17 07:41 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
> +  async self ({ params, response, auth }) {
где? не вижу?

2018-12-17 07:41 UTC, GerashenkoVladimir commented on app/Models/Hooks/LotHook.js
> +const LotHook = {};
через обычные инстансные методы работает

2018-12-17 07:41 UTC, GerashenkoVladimir commented on test/functional/http/lot.spec.js
> +    data: {
и по твоему это норм что оно два раза в дату завернуто?

2018-12-17 07:41 UTC, GerashenkoVladimir commented on test/unit/validators/lot.spec.js
> +  response.assertStatus(400);
переопредели в валидаторе
400 означает например синтаксическую ошибку а 422 Unprocessable Entity

2018-12-17 18:22 UTC, GerashenkoVladimir approved these changes

2018-12-17 18:46 UTC, merged