jobs flow
Insidexa/auction pull request #6
Opened 2018-12-22 06:36 UTC by Insidexa

2018-12-23 11:38 UTC, GerashenkoVladimir requested changes

2018-12-23 11:38 UTC, GerashenkoVladimir commented on app/Controllers/Http/BidController.js
>  const BidPriceSmallerException = use('App/Exceptions/BidPriceSmallerException');
я бы сделал какую то более общую ошибку но одну.
BidException или BidPriceException и при инициализации выбрасывал эексепшен с разным месседжем
та и вроде как на ошибку валидации очень похоже, почему бы не засунуть это в валидатор. что думаешь об этом?

2018-12-23 11:38 UTC, GerashenkoVladimir commented on app/Controllers/Http/BidController.js
> +      const data = await LotJobService.getLotJobsIds(lot.id);
не мешало бы это инкапсулировать куда ни будь
например в Order afterCreate

2018-12-23 11:38 UTC, GerashenkoVladimir commented on app/Controllers/Http/BidController.js
> +      const data = await LotJobService.getLotJobsIds(lot.id);
как по мне много логики перекладываешь на контроллер

2018-12-23 11:38 UTC, GerashenkoVladimir commented on app/Controllers/Http/BidController.js
> +      const data = await LotJobService.getLotJobsIds(lot.id);
не раздувай так методы
пусть будет больше мелких методов .....будет гораздо читабельнее....тем более это екшен контроллера, а как нам известно контроллер должен быть тонким:)

2018-12-23 11:38 UTC, GerashenkoVladimir commented on app/Controllers/Http/BidController.js
> +      const { jobEndId } = JSON.parse(data);
я думаю надо бы возвращать сразу распарсеные айдишники, что бы клиентский код не заморачивался с джейсоном

2018-12-23 11:38 UTC, GerashenkoVladimir commented on app/Jobs/LotEndJob.js
> +    const bidLotWinner = await BidWinnerService.getWinnerBid(lot);
а если сделаем вот так lot.winnerBid().fetch()?
вроде как логично что лот может знать "свою" выиграшную ставку
и как по мне нормально бы смотрелся метод lot.hasWinner()

2018-12-23 11:38 UTC, GerashenkoVladimir commented on app/Services/BidWinnerService.js
>      return await Bid.query().withMaxPriceOnLot(lot.id).first();
lot.bids().withMaxPriceOnLot().first()
по сути lot.bids() если не ошибаюсь возвращает тот же query и от него должны тоже работать скоупы

2018-12-23 11:38 UTC, GerashenkoVladimir commented on app/Services/LotJobService.js
> +    return await Redis.get(this.getLotJobKey(lotId));
разве сам Kue не умеет доставать джобы?

2018-12-23 11:38 UTC, GerashenkoVladimir commented on test/functional/http/bid.spec.js
>    const user = await Factory.model('App/Models/User').create({
а разве тебе есть дело до того какие там у юзера пароли имейлы и тд?
на сколько я понимаю что тебе достаточно того что они разные

2018-12-23 11:38 UTC, GerashenkoVladimir commented on test/functional/http/bid.spec.js
> +  Queue.testMode.clear();
а зачем ты после каждого теста свитчишь режимы воркера?

2018-12-23 11:38 UTC, GerashenkoVladimir commented on test/functional/http/bid.spec.js
> +  await makeLotTestJobs(Queue, lotProcess);
если бы ты повесил эти джобы на хуки модели, не пришлось это делать какждый раз в ручную

2018-12-23 11:38 UTC, GerashenkoVladimir commented on test/utils/utils.js
> +    return Promise.resolve(job);
async/await

2018-12-23 11:38 UTC, GerashenkoVladimir commented on test/functional/jobs/lot-end-job.spec.js
> +  await new Promise((resolve) => {
тут без промиса вообще никак?

2018-12-23 12:12 UTC, Insidexa commented on app/Jobs/LotEndJob.js
> +    const bidLotWinner = await BidWinnerService.getWinnerBid(lot);
так толку от hasWinner будет мало, он только лазит за тем что бы сказать да / нет

2018-12-23 12:14 UTC, Insidexa commented on test/functional/http/bid.spec.js
> +  await makeLotTestJobs(Queue, lotProcess);
говорил ты мне другое, удалить джобы с хуков, это точно помню

2018-12-23 12:57 UTC, Insidexa commented on app/Controllers/Http/BidController.js
>  const BidPriceSmallerException = use('App/Exceptions/BidPriceSmallerException');
я думал жто засунуть в валидатор, но потом мне прийдется 2 раза лот тягать с базы или его в валидаторе прокидывать в request что бы еще раз в контроллере не тянуть

2018-12-23 12:58 UTC, Insidexa commented on app/Controllers/Http/BidController.js
> +      const data = await LotJobService.getLotJobsIds(lot.id);
была мысля, потом подумал зачем это в OrderListener и удалил

2018-12-23 12:58 UTC, Insidexa commented on app/Services/LotJobService.js
> +    return await Redis.get(this.getLotJobKey(lotId));
так суть то не в этом, я там вытягиваю для лота ид джоб старта и кокнчания, kue не причем

2018-12-23 13:01 UTC, Insidexa commented on test/functional/jobs/lot-end-job.spec.js
> +  await new Promise((resolve) => {
вообще, та колбек прокидывается в джобу, в hooks.js есть это

2018-12-23 13:13 UTC, Insidexa commented on test/functional/http/bid.spec.js
> +  Queue.testMode.clear();
это чистится массив джобов

2018-12-23 14:44 UTC, Insidexa commented on app/Controllers/Http/BidController.js
> +      const data = await LotJobService.getLotJobsIds(lot.id);
+

2018-12-23 14:44 UTC, Insidexa commented on app/Controllers/Http/BidController.js
> +      const data = await LotJobService.getLotJobsIds(lot.id);
+

2018-12-23 14:44 UTC, Insidexa commented on app/Controllers/Http/BidController.js
> +      const data = await LotJobService.getLotJobsIds(lot.id);
+

2018-12-23 14:44 UTC, Insidexa commented on app/Controllers/Http/BidController.js
> +      const { jobEndId } = JSON.parse(data);
+

2018-12-23 14:44 UTC, Insidexa commented on app/Services/BidWinnerService.js
>      return await Bid.query().withMaxPriceOnLot(lot.id).first();
+

2018-12-23 14:44 UTC, Insidexa commented on test/functional/http/bid.spec.js
>    const user = await Factory.model('App/Models/User').create({
+

2018-12-23 14:44 UTC, Insidexa commented on test/utils/utils.js
> +    return Promise.resolve(job);
+

2018-12-23 15:51 UTC, GerashenkoVladimir commented on test/functional/http/bid.spec.js
> +  Queue.testMode.clear();
ну есть просто queue.testMode.clear()
этого вроде как достаточно должно быть

2018-12-23 16:00 UTC, GerashenkoVladimir commented on test/functional/jobs/lot-end-job.spec.js
> +  await new Promise((resolve) => {
await job.handle({
        data: {
          id: lotInProcess.id,
        },
      }, () => {});
ну с колбеком и так можно

2018-12-24 05:36 UTC, Insidexa commented on test/functional/jobs/lot-end-job.spec.js
> +  await new Promise((resolve) => {
+

2018-12-24 05:36 UTC, Insidexa commented on app/Controllers/Http/BidController.js
>  const BidPriceSmallerException = use('App/Exceptions/BidPriceSmallerException');
+

2018-12-24 07:47 UTC, GerashenkoVladimir requested changes

2018-12-24 07:47 UTC, GerashenkoVladimir commented on app/Services/BidWinnerService.js
> +    return await lot.bids().withMaxPriceOnLot(lot.id).first();
ну так уже не надо и лот ид прокидывать раз оно от этого же лота и пытается сфетчить

2018-12-24 07:51 UTC, Insidexa commented on app/Services/BidWinnerService.js
> +    return await lot.bids().withMaxPriceOnLot(lot.id).first();
+

2018-12-24 07:51 UTC, GerashenkoVladimir approved these changes

2018-12-24 07:52 UTC, merged