bids collection update with ws on lot page
Insidexa/auction pull request #8
Opened 2018-12-24 12:47 UTC by Insidexa

2018-12-26 18:53 UTC, GerashenkoVladimir requested changes

2018-12-26 18:53 UTC, GerashenkoVladimir commented on README.md
> +const ws = Ws('ws://localhost:3333', { path: 'ws' });
как бы так себе хардкодить хост:порт ....но к фронту придираться не буду

2018-12-26 18:53 UTC, GerashenkoVladimir commented on app/Controllers/Http/BidController.js
> +    Event.fire('lotPage::onCreateBid', bid);
а если не сохранится?

2018-12-26 18:53 UTC, GerashenkoVladimir commented on app/Validators/CustomRules/BidPriceRule.js
> +  const bidMaxPriceLot = await lot.bids().withMaxPriceOnLot().first();
это из прошлого ПР-а косяки?

2018-12-26 19:03 UTC, Insidexa commented on README.md
> +const ws = Ws('ws://localhost:3333', { path: 'ws' });
ну это же ридми

2018-12-26 19:23 UTC, Insidexa commented on app/Controllers/Http/BidController.js
> +    Event.fire('lotPage::onCreateBid', bid);
кинет исключение и не выполнится ивент

2018-12-26 21:10 UTC, Insidexa commented on app/Validators/CustomRules/BidPriceRule.js
> +  const bidMaxPriceLot = await lot.bids().withMaxPriceOnLot().first();
да, не заметил

2018-12-26 21:12 UTC, Insidexa commented on README.md
> +const ws = Ws('ws://localhost:3333', { path: 'ws' });
+

2018-12-27 08:18 UTC, GerashenkoVladimir commented on README.md
> +const ws = Ws('ws://localhost:3333', { path: 'ws' });
сори затупил)
парсится как полноценный код....не обратил внимание на название

2018-12-27 08:19 UTC, GerashenkoVladimir commented on app/Controllers/Http/BidController.js
> +    Event.fire('lotPage::onCreateBid', bid);
не очевидно
тогда б уже назвал createBidOrFail()

2018-12-27 08:20 UTC, GerashenkoVladimir approved these changes

2018-12-27 08:22 UTC, merged