order flow
Insidexa/auction pull request #9
Opened 2018-12-27 09:51 UTC by Insidexa

2018-12-27 20:01 UTC, GerashenkoVladimir requested changes

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
>        delete lotResponse.order;
что это такое?

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Controllers/Http/OrderController.js
> +    const orderRequestData = this.filterOrderFields(request);
order я думаю надо создавать автоматически
так как по правилам аукционов вроде как сделанную ставку отменить нельзя

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Controllers/Http/OrderController.js
> +    const bidWinner = await lot.bids().withMaxPriceOnLot().first();
любая ставка с максимальной ценой?
не зависимо от того есть ли победившая ставка?
проверяешь ли статус ордера?

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Controllers/Http/OrderController.js
> +    order.arrival_type = orderRequestData.arrival_type;
order.merge({......})

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Controllers/Http/OrderController.js
> +    const order = await Order.find(id);
разрешаешь апдейтить ордер в любом статусе?

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Controllers/Http/OrderController.js
> +  async sellerExecute ({ params, response }) {
это обычный апдейт ордера, пусть и со специфичной логикой
не по ресту

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Controllers/Http/OrderController.js
> +  async customerReceive ({ params, response }) {
то же что и выше

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Middleware/CanChangeOrderStatusMiddleware.js
> +    const statusNeeded = parseInt(statusNeededStr, 0);
что такое ноль?
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/parseInt

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Middleware/CanChangeOrderStatusMiddleware.js
> +      case 'customer':
хардкод

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Middleware/CanChangeOrderStatusMiddleware.js
> +        const lot = await order.lot().fetch();
вложенные условные операторы не хорошо, читать тяжело

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Middleware/CanChangeOrderStatusMiddleware.js
> +        const canSellerUpdateOrder = lot.user_id === user.id && order.lot_id === lot.id;
order.lot_id === lot.id--- ты же лот с ордера сфетчил? как оно может быть не равно?

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Middleware/CanCreateOrderMiddleware.js
> +    const { id } = auth.user;
userId
ты через 10 строк забудешь что такое id

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Middleware/CanCreateOrderMiddleware.js
> +class CanCreateOrderMiddleware {
если будешь создавать автоматически это вообще не понадобится

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Middleware/CanCreateOrderMiddleware.js
> +      && bidWinner.lot_id === lot_id;
bidWinner.lot_id === lot_id то же что и про лот я писал ... ты только что его сфетчил

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Validators/OrderCreate.js
> +      arrival_type: 'required',
arrival type (either pickup or one of the post delivery companies: Royal Mail, United States Postal Service, DHL Express)
где это отражено? по хорошему даже в таблицу можно отдельную

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Validators/OrderCreate.js
> +      arrival_type: 'required',
ну и валидировать тоже

2018-12-27 20:01 UTC, GerashenkoVladimir commented on app/Validators/OrderUpdate.js
> +      arrival_type: 'required',
тоже самое

2018-12-27 20:03 UTC, Insidexa commented on app/Middleware/CanChangeOrderStatusMiddleware.js
> +    const statusNeeded = parseInt(statusNeededStr, 0);
eslint матюкается

2018-12-27 20:06 UTC, Insidexa commented on app/Controllers/Http/OrderController.js
> +    const bidWinner = await lot.bids().withMaxPriceOnLot().first();
я тут его создаю, по умолчанию в базе будет PENDING_STATUS

2018-12-27 20:08 UTC, Insidexa commented on app/Controllers/Http/OrderController.js
> +    const order = await Order.find(id);
нет, мидлваре это чекает, в роутах указан статус который нужен что бы установить след. статус

2018-12-27 20:11 UTC, Insidexa commented on app/Validators/OrderCreate.js
> +      arrival_type: 'required',
у тз про выбор доставки и адреса ничего не сказано, просто текст

2018-12-27 20:19 UTC, Insidexa commented on app/Controllers/Http/LotController.js
>        delete lotResponse.order;
кто может видеть order на странице лота, если текущий юзер выиграл лот, то только он может получить инфу order

2018-12-27 20:37 UTC, GerashenkoVladimir commented on app/Controllers/Http/LotController.js
>        delete lotResponse.order;
какие то странные манипуляции....зачем его изначально фетчить? может сначала решение принять а потом фетчить?

2018-12-27 20:41 UTC, GerashenkoVladimir commented on app/Controllers/Http/OrderController.js
> +    const bidWinner = await lot.bids().withMaxPriceOnLot().first();
а если нет победившей ставки? тебя получается устроит последняя наивысшая

2018-12-27 20:42 UTC, GerashenkoVladimir commented on app/Controllers/Http/OrderController.js
> +    const order = await Order.find(id);
позже посмотрел уже

2018-12-27 20:43 UTC, GerashenkoVladimir commented on app/Validators/OrderCreate.js
> +      arrival_type: 'required',
я по твоему откуда скопировал? там четко указаны типы доставки

2018-12-27 20:43 UTC, GerashenkoVladimir commented on app/Validators/OrderCreate.js
> +      arrival_type: 'required',
я у тебя их не вижу

2018-12-27 20:54 UTC, GerashenkoVladimir commented on app/Controllers/Http/OrderController.js
> +    const bidWinner = await lot.bids().withMaxPriceOnLot().first();
и как так выходит лот закрыт а заказ не сформирован даже
та и может вообще не быть сформирован

2018-12-28 05:37 UTC, Insidexa commented on app/Validators/OrderCreate.js
> +      arrival_type: 'required',
увидел, сорян

2018-12-28 06:06 UTC, Insidexa commented on app/Controllers/Http/OrderController.js
> +    const bidWinner = await lot.bids().withMaxPriceOnLot().first();
если нету никакой ставки, то не даст создать order

2018-12-28 07:32 UTC, Insidexa commented on app/Controllers/Http/OrderController.js
> +    const orderRequestData = this.filterOrderFields(request);
ставка не отменится

2018-12-28 07:44 UTC, Insidexa commented on app/Controllers/Http/OrderController.js
> +  async sellerExecute ({ params, response }) {
предлагаешь передавать status в request`e ? или инкрементить статус как бы при апдейте
тогда в update action будет каша, обновление адреса пока pending status + смена статусов
погуглив насчет rest api partial update, пришел к выводу что рест это не предусматривает
т.е. все придумывают, даже есть отдельные micro endpoint примеры для смены статусов как   выше

2018-12-28 10:14 UTC, Insidexa commented on app/Controllers/Http/LotController.js
>        delete lotResponse.order;
ну как бы я не могу узнать выиграл ли юзер без данных по order, темболее на странице лота нужен показ инфы об order
если брать order отдельным роутом, то там тоже будут такие странные манипуляции, и seller может order посмотреть и покупатель

2018-12-28 14:06 UTC, Insidexa commented on app/Controllers/Http/OrderController.js
> +    const orderRequestData = this.filterOrderFields(request);
+

2018-12-28 14:06 UTC, Insidexa commented on app/Controllers/Http/OrderController.js
> +    order.arrival_type = orderRequestData.arrival_type;
преписал

2018-12-28 14:06 UTC, Insidexa commented on app/Middleware/CanChangeOrderStatusMiddleware.js
> +      case 'customer':
+

2018-12-28 14:06 UTC, Insidexa commented on app/Middleware/CanChangeOrderStatusMiddleware.js
> +        const lot = await order.lot().fetch();
+

2018-12-28 14:06 UTC, Insidexa commented on app/Middleware/CanChangeOrderStatusMiddleware.js
> +        const canSellerUpdateOrder = lot.user_id === user.id && order.lot_id === lot.id;
+

2018-12-28 14:06 UTC, Insidexa commented on app/Middleware/CanCreateOrderMiddleware.js
> +    const { id } = auth.user;
+

2018-12-28 14:06 UTC, Insidexa commented on app/Middleware/CanCreateOrderMiddleware.js
> +class CanCreateOrderMiddleware {
+

2018-12-28 14:07 UTC, Insidexa commented on app/Middleware/CanCreateOrderMiddleware.js
> +      && bidWinner.lot_id === lot_id;
+

2018-12-28 14:07 UTC, Insidexa commented on app/Validators/OrderCreate.js
> +      arrival_type: 'required',
+

2018-12-28 14:07 UTC, Insidexa commented on app/Validators/OrderCreate.js
> +      arrival_type: 'required',
+

2018-12-28 14:07 UTC, Insidexa commented on app/Validators/OrderUpdate.js
> +      arrival_type: 'required',
+

2018-12-28 14:18 UTC, Insidexa commented on app/Middleware/CanCreateOrderMiddleware.js
> +class CanCreateOrderMiddleware {
+

2018-12-29 09:49 UTC, GerashenkoVladimir requested changes

2018-12-29 09:49 UTC, GerashenkoVladimir commented on app/Validators/OrderUpdate.js
> +      arrival_type_id: 'required|integer',
мы делали кастомное правило такого вида 
exists:posts,id
которое проверяло есть ли в базе такая запись

2018-12-29 10:24 UTC, Insidexa commented on app/Validators/OrderUpdate.js
> +      arrival_type_id: 'required|integer',
+

2018-12-29 15:56 UTC, GerashenkoVladimir approved these changes

2018-12-29 16:39 UTC, merged